// Seed patterns. Tiles are greyscale so the renderer can tint them with any colour.
module.exports = [
  {
    name: 'Classic Stripes',
    category: 'Stripes',
    file: 'stripes.svg',
    w: 80,
    h: 80,
    description: 'Wide vertical stripes.',
  },
  {
    name: 'Fine Pinstripe',
    category: 'Stripes',
    file: 'pinstripe.svg',
    w: 40,
    h: 40,
    description: 'Thin, subtle vertical lines.',
  },
  {
    name: 'Chevron Zigzag',
    category: 'Geometric',
    file: 'chevron.svg',
    w: 80,
    h: 40,
    description: 'Repeating zigzag bands.',
  },
  {
    name: 'Diamond Lattice',
    category: 'Geometric',
    file: 'diamond.svg',
    w: 60,
    h: 60,
    description: 'Outlined diamond repeat.',
  },
  {
    name: 'Modern Grid',
    category: 'Geometric',
    file: 'grid.svg',
    w: 40,
    h: 40,
    description: 'Clean square grid.',
  },
  {
    name: 'Polka Dots',
    category: 'Playful',
    file: 'polka-dot.svg',
    w: 50,
    h: 50,
    description: 'Offset dot repeat, great for kids rooms.',
  },
  {
    name: 'Falling Leaves',
    category: 'Floral',
    file: 'leaf.svg',
    w: 100,
    h: 100,
    description: 'Simple botanical leaf motif.',
  },
  {
    name: 'Brick Lay',
    category: 'Textured',
    file: 'brick.svg',
    w: 80,
    h: 40,
    description: 'Running-bond brick effect.',
  },
].map(({ file, w, h, ...rest }) => ({
  ...rest,
  imageUrl: `/static/patterns/${file}`,
  tileSize: { width: w, height: h },
}));
